version: {build}

init:
  - ps: $env:POM_ARTIFACT = ([xml](Get-Content .\pom.xml)).project.artifactId
  - ps: $env:POM_VERSION = ([xml](Get-Content .\pom.xml)).project.version
  - ps: Update-AppveyorBuild -Version "$env:POM_VERSION.$env:APPVEYOR_BUILD_NUMBER"

build_script:
  - mvn clean install
test_script:
#  - mvn clean install --batch-mode
cache:
  - C:\Users\appveyor\.m2
atrifacts:
  - path: .\target\$env:POM_ARTIFACT-$env:POM_VERSION.jar
    name: $env:POM_ARTIFACT-$env:POM_VERSION.jar
