version: '{build}'

build_script:
  - mvn clean install
test_script:
#  - mvn clean install --batch-mode
after_build:
  - ps: $env:pom_artifactId = ([xml](Get-Content .\pom.xml)).project.artifactId
  - ps: $env:pom_version = ([xml](Get-Content .\pom.xml)).project.version
  - ps: $env:versionStr = "$env:pom_version-$env:APPVEYOR_BUILD_NUMBER"
  - ps: Update-AppveyorBuild -Version "$env:versionStr"
  - set fileName=%pom_artifactId%-%versionStr%.jar
cache:
  - C:\Users\appveyor\.m2
artifacts:
  - path: .\target\$(fileName)
    name: $(fileName)
